cloud:
  aws:
    s3:
      bucket:
        name: "devshare-pangnem"
        imageDir: "images"
        fileDir: "files"
    region:
      static: "ap-northeast-2"
    stack: # CloudFormation 구성 설정 해제
      auto: false
    credentials:
      accessKey:
      secretKey:
      instanceProfile: true # aws configure list로 확인한 key들을 사용
      useDefaultAwsCredentialsChain: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:file:~/data/devshare
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:file:~/data/devshare-test
  jpa:
    hibernate:
      ddl-auto: create-drop

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
